### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheMispeled** [kdenzel/DrawPerfectCyrcle#4] opened 2023-08-02 20:59 UTC
Exception in thread "main" java.lang.UnsupportedClassVersionError: de/kswmd/drawperfectcycle/DrawPerfectCyrcle has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by MajliTech** [comment] 2023-08-03 15:51
Your Java runtime needs upgrading. Please download [Java Runtime Environment 11](https://adoptium.net/marketplace/?version=11), and check if you are using the newer version by running `java --version` in your command prompt. If not, please post a reply to this issue for more help.

[Quick download for 64-bit systems](https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20%2B8/OpenJDK11U-jre_x64_windows_hotspot_11.0.20_8.msi)
[Quick download for 32-bit systems](https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20%2B8/OpenJDK11U-jre_x86_windows_hotspot_11.0.20_8.msi)
 
And also, for future refrence:
1. Don't use ***Error*** as an issue name. Use something more descriptive.
2. Put your logs in ` ``` ` next time, like
` ```logs...``` `

**Comment by MajliTech** [comment] 2023-08-06 13:58
If the issue is resolved, close it as completed.

**Closed as completed** 2023-08-06 14:03 UTC
